name: Update bucket
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Excavator
      uses: ScoopInstaller/Scoop-GithubActions@e174c3bef2aeec16a40f2f075cafa167733f0a3e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_EMAIL: ${{ secrets.EMAIL }}
